### GET All Books
GET http://127.0.0.1:8000/api/books/

### GET Book by ID
GET http://127.0.0.1:8000/api/books/4/

### GET Books by Author
GET http://127.0.0.1:8000/api/books/?author_first_name=Muhammad

### GET Books by Author National
GET http://127.0.0.1:8000/api/books/?author_nationality=Bangladesh

### POST Single Book
POST http://127.0.0.1:8000/api/books/create/
Content-Type: application/json

{
  "title": "A World of Three Zeros",
  "published_date": "2017-09-26",
  "isbn": "9781541742390",
  "author": {
    "first_name": "Muhammad",
    "last_name": "Yunus",
    "nationality": "Bangladesh"
  }
}

### POST Bulk Book
POST http://127.0.0.1:8000/api/books/bulk/
Content-Type: application/json

[
  {
    "title": "Pather Panchali",
    "published_date": "1929-12-25",
    "isbn": "9788184003901",
    "author": {
      "first_name": "Bibhutibhushan",
      "last_name": "Bandyopadhyay",
      "nationality": "Bangladesh"
    }
  },
  {
    "title": "Gitanjali",
    "published_date": "1910-08-14",
    "isbn": "9780140449883",
    "author": {
      "first_name": "Rabindranath",
      "last_name": "Tagore",
      "nationality": "Bangladesh"
    }
  },
  {
    "title": "Debi",
    "published_date": "1993-02-14",
    "isbn": "9789847010809",
    "author": {
      "first_name": "Humayun",
      "last_name": "Ahmed",
      "nationality": "Bangladesh"
    }
  },
  {
    "title": "Lajja",
    "published_date": "1993-09-12",
    "isbn": "9780143032653",
    "author": {
      "first_name": "Taslima",
      "last_name": "Nasrin",
      "nationality": "Bangladesh"
    }
  },
  {
    "title": "Srikanta",
    "published_date": "1917-01-10",
    "isbn": "9788129147494",
    "author": {
      "first_name": "Sarat Chandra",
      "last_name": "Chattopadhyay",
      "nationality": "Bangladesh"
    }
  },
  {
    "title": "Chander Pahar",
    "published_date": "1937-06-20",
    "isbn": "9788129120947",
    "author": {
      "first_name": "Bibhutibhushan",
      "last_name": "Bandyopadhyay",
      "nationality": "Bangladesh"
    }
  },
  {
    "title": "Shesher Kobita",
    "published_date": "1929-04-17",
    "isbn": "9788129112058",
    "author": {
      "first_name": "Rabindranath",
      "last_name": "Tagore",
      "nationality": "Bangladesh"
    }
  },
  {
    "title": "Deyal",
    "published_date": "2013-05-22",
    "isbn": "9789847012728",
    "author": {
      "first_name": "Humayun",
      "last_name": "Ahmed",
      "nationality": "Bangladesh"
    }
  },
  {
    "title": "Ami Birangona Bolchi",
    "published_date": "1995-12-15",
    "isbn": "9788179761594",
    "author": {
      "first_name": "Nilima",
      "last_name": "Ibrahim",
      "nationality": "Bangladesh"
    }
  },
  {
    "title": "Madhyabartini",
    "published_date": "1963-07-25",
    "isbn": "9788184985764",
    "author": {
      "first_name": "Narayan",
      "last_name": "Sanyal",
      "nationality": "Bangladesh"
    }
  }
]

### UPDATE Book
PATCH http://127.0.0.1:8000/api/books/7/
Content-Type: application/json

{
  "published_date": "2024-01-01"
}

### FULL UPDATE Book
PUT http://127.0.0.1:8000/api/books/6/
Content-Type: application/json

{
  "title": "Building Social Business - Updated",
  "published_date": "2010-05-11",
  "isbn": "9781586488246U",
  "author": {
    "first_name": "Muhammad",
    "last_name": "Yunus",
    "nationality": "Bangladesh"
  }
}

### DELETE Book
DELETE http://127.0.0.1:8000/api/books/6/