### GET All Books
GET http://127.0.0.1:8000/api/books/

### GET Book by ID
GET http://127.0.0.1:8000/api/books/4/

### POST New Book
POST http://127.0.0.1:8000/api/books/
Content-Type: application/json

{
  "title": "The Alchemist",
  "author": "Paulo Coelho",
  "published_date": "1988-01-01",
  "isbn": "9780062315007"
}

### UPDATE Book
PATCH http://127.0.0.1:8000/api/books/1/
Content-Type: application/json

{
  "title": "The world of Three Zeros",
  "author": "Muhammad Yunus",
  "published_date": "2017-09-01",
  "isbn": "9781476753171"
}